### ISSUE TITLE
DJIMediaFile's name do not match the true file's name in aircraft's sd card

### ISSUE THREAD

**Issue by PandaraWen** [dji-sdk/Mobile-SDK-iOS#120] opened 2017-06-29 10:40 UTC
## Description

I got `DJIMediaFile` obj in `DJICamera`'s delegate method:

```Swift
func camera(_ camera: DJICamera, didGenerateNewMediaFile newMedia: DJIMediaFile) {
    NSlog("Generate new media file: \(newMedia.fileName)")
}
```

But after I searching in the sd card, I found that the true image file in sd card had a different file name.

## Environment

I am using DJI iOS SDK 4.2, Phantom 4 Pro, iPhone 6 with iOS 10.3.2, Xcode 9.0 beta.

**Comment by XietongLU** [comment] 2017-07-18 12:20
We are looking into this issue. It is caused by a change in firmware. If you just want to distinguish different photos, you can also rely on the index.

**Comment by XietongLU** [comment] 2017-07-18 12:44
The fix will be included in the next release.

**Closed by XietongLU** 2017-07-18 12:44 UTC
