### ISSUE TITLE
DJIWaypointMissionOperator currentState is incorrect and prevents further missions from being loaded...

### ISSUE THREAD

**Issue by jgrantr** [dji-sdk/Mobile-SDK-iOS#99] opened 2017-05-01 22:09 UTC
When using the DJIWaypointMissionOperator to fly missions, the state of the operator and the state of the underlying mission can get out of sync.  If the mission is paused just before the aircraft reaches the final waypoint, the DJIWaypointMissionOperator will go into the "Paused" state, but the momentum of the aircraft will cause it to reach its final waypoint, it will execute the actions, and then the mission will actually END while the operator still says it is PAUSED.  So, when you call "resumeMissionWithCompletion:", it will actually throw an error saying that no mission is running.  The issue is not so much with what happens, as with the fact that the operator will still say it is paused, even though it has completed the missions.  It also doesn't call any of the listeners (like the finished listener) even though the mission clearly finished.  What is more troublesome, is that I don't know how to get it OUT of this state, as if I try to call "loadMission" while it is in this state, it gives back the somewhat unhelpful error of:

Error Domain=DJISDKMissionErrorDomain Code=-5024 "Command cannot be executed.(code:-5024)" UserInfo={NSLocalizedDescription=Command cannot be executed.(code:-5024)}

I can reproduce this every time with a simple waypoint mission that has 2 waypoints (they should be several hundred feet apart) with the auto flight speed set to 14 m/s and then have 3 actions on the last waypoint:
 * rotate gimbal to -90 degrees
* rotate the aircraft to a given heading (doesn't really matter which heading)
* take a photo

What I would expect to happen is that if the mission finishes while the operator is paused, the listeners would be called so that I can keep track of things like if the actions were performed or not, etc, and then calling RESUME would not error out, but would simply transition the operator back to the ReadyToUpload state so that I can load new missions and continue on from there.

DJI iOS SDK version: 4.0.1
DJI Product: DJI Phantom 4 Pro
iOS System version: iOS 10.2.1
iOS Device type: iOS simulator (simulating an iPad Air 2 running iOS 10.2.1)
Xcode version: 8.2.1

Please let me know if you have any questions.  Also, if there are workarounds when it gets in this state, I would love to know what they are.

**Comment by jgrantr** [comment] 2017-05-03 17:42
Any updates on this issue?

**Comment by XietongLU** [comment] 2017-05-04 04:05
@jgrantr to help us reproduce this issue, could you provide us more information about "If the mission is paused just before the aircraft reaches the final waypoint"? In your example, when should I call the pause? 
Did you try to call stopMission?

**Comment by XietongLU** [comment] 2017-05-04 08:36
@jgrantr The issue is reproduced and fixed. Sorry that we don't cover this corner case before. The fix will be included in the next release.

**Closed by XietongLU** 2017-05-04 08:36 UTC
