### ISSUE TITLE
sendDataFromMobileToOnboard compilation block called twice

### ISSUE THREAD

**Issue by jaesik-hwang** [dji-sdk/Mobile-SDK-iOS#266] opened 2018-06-26 07:02 UTC
- DJI-SDK-iOS (4.5.2)
  - DJI-UXSDK-iOS (4.5.1)
 - M600 Pro(F/W 3.2.41.13)
 - LightBridge 2
 - iPad mini 4

When I call 
[self.sdk sendDataFromMobileToOnboard:data withCompletion:completion];

it's completion block is called twice even 'oboard sdk' receives only once.

And it looks like following delegate method is called twice even 'sendDataToMSDK(,)' is called once at onboard side.

- (void)onboardSDKDevice:(DJIOnboardSDKDevice *)osdkDevice didSendDataToMobile:(NSData *)data

**Comment by lijia6745** [comment] 2018-06-26 12:10
Will fix it next version.

**Comment by dji-dev** [comment] 2018-12-17 07:35
Hi @jaesik-hwang , the issue is fixed in the latest iOS SDK 4.8.1 version. Please try again. If you still have more issues related to DJI SDK, please help to report them to dev@dji.com, as it's our official channel for developers to request DJI SDK support now.

**Closed by dji-dev** 2018-12-17 07:35 UTC
